const arr=[
    {
        id:1,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Reliance-3.png"

    },
    {
        id:2,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/HDFC-Life-Insurance.png"

    },
    {
        id:3,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Transperfect-2.png"

    },
    {
        id:4,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Volkswagen-1.png"

    },
    {
        id:5,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Lionbridge-1.png"

    },
    {
        id:6,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Yanmar-1.png"

    },
    {
        id:7,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/The-Art-of-Living.png"

    },
    {
        id:8,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Sodexo-1.png"

    },
    {
        id:9,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/HT-Media-1.png"

    },
    {
        id:10,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/LT-2.png"

    },
    {
        id:11,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Kotak-2.png"

    },
    {
        id:12,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Language-Connect-1.png"

    },
    {
        id:13,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Aditya-Birla-Capital.png"

    },
    {
        id:14,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Bookmyshow-2.png"

    },
    {
        id:15,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Globe-Language-Services.png"

    },
    {
        id:16,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/BG-Communications-1.png"

    },
    {
        id:17,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Birla-Sun-Life-1.png"

    },
    {
        id:18,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/OTIS-2.png"

    },
    
    {
        id:19,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/1-Stop-Asia.png"
    },
    {
        id:20,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/911-Interpreter.png"
    },
    {
        id:21,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/ADT-International.png"
    },
    {
        id:22,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/AE-Translation.png"
    },
    {
        id:23,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Alliance.png"
    },
    {
        id:24,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Apple-Localization.png"
    },
    {
        id:25,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Asia-Localize.png"
    },
    {
        id:26,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Babel.png"
    },
    {
        id:27,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Bayantech.png"
    },
    {
        id:28,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/California.png"
    },
    {
        id:29,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/CCJK.png"
    },
    {
        id:30,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Codex-Global.png"
    },
    {
        id:31,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Convergent-Group.png"
    },
    {
        id:32,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Craft-Translation.png"
    },
    {
        id:33,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/ek-Translations.png"
    },
    {
        id:34,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/EQHO.png"
    },
    {
        id:35,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/FCI-Language-Expert.png"
    },
    {
        id:36,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Gercek-Tercume.png"
    },
    {
        id:37,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Global-Vision.png"
    },
    {
        id:38,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Idea-Institute.png"
    },
    {
        id:39,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Indian-Oil-2.png"
    },
    {
        id:40,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Language-International.png"
    },
    {
        id:41,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/LeReve-Translation.png"
    },
    {
        id:43,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Linfox.png"
    },
    {
        id:41,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Lingperfect.png"
    },
    {
        id:42,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/LocMore.png"
    },
    {
        id:43,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Localize-Group.png"
    },
    {
        id:44,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/MidLocalize.png"
    },
    {
        id:45,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/NuFantex.png"
    },
    {
        id:46,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/ParleClair.png"
    },
    {
        id:47,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Simpson-Soft-UK.png"
    },
    {
        id:48,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Stem.png"
    },
    {
        id:49,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Studio-Tre.png"
    },
    {
        id:50,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Telelingua.png"
    },
    {
        id:51,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Universum-Translation.png"
    },
    {
        id:52,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Verbatim.png"
    },
    {
        id:53,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Dua-Associates.png"
    },
    {
        id:54,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/DR-Localization-Logo.png"
    },
    {
        id:55,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Explayin-Logo.png"
    },
    {
        id:56,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/IIFL-Finance-Logo.png"
    },
    {
        id:57,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Jonckers-Logo.png"
    },
    {
        id:58,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/JustAct-Logo.png"
    },
    {
        id:59,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/MacLeods-Logo.png"
    },
    {
        id:60,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/People-Strong-Logo.png"
    },
    {
        id:61,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Star-Union-Dai-Chi-Logo.png"
    },
    {
        id:62,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Yokogawa-Logo.png"
    },
    {
        id:63,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/Tata-Motors-Finance-Logo.png"
    },
    {
        id:64,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2022/09/KLG-Spice-Logo.png"
    },
    {
        id:65,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2023/01/CQ-Fluency.png"
    },
    {
        id:66,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2023/01/Tata-AIG-Insurance.png"
    },
    {
        id:67,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2023/01/RWS.png"
    },
    {
        id:68,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2023/01/Megalexis.png"
    },
    {
        id:69,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2023/01/Hurixs.png"
    },
    {
        id:70,
        link:"https://parikhinfosolutions.com/wp-content/uploads/2020/10/Globe-Language-Services.png"
    },
    // {
    //     id:71,
    //     link:""
    // },
    // {
    //     id:72,
    //     link:""
    // },
   
]
export default arr;